name: Action Cond

on: [push, pull_request]

jobs:
  add_label:
    runs-on: ubuntu-latest 
    steps:
      - name: Determine Checkout Depth
        uses: haya14busa/action-cond@v1.0.2
        id: fetchDepth
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: '0'  # string value
          if_false: '1' # string value

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: ${{ steps.fetchDepth.outputs.value }}
          token: ${{ secrets.ACCESS_TOKEN }}