name: Auto Accept Collabs

on:
  schedule:
    - cron: "0 1 * * MON-FRI" # Runs at 01:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v3
      - name: Auto Accept Collabs
        uses: kbrashears5/github-action-auto-accept-collabs@v1.0.0
        with:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}