name: Checkout

on:
  push:
    branches:
      - 'dev' # For the dev branch
  schedule:
    - cron: "0 0 * * MON-FRI" # Runs at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          date > checkout-workflow.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated checkout workflow file"
          git push
