name: Close Pull Request

on:
  pull_request_target:
    types: [opened, reopened]
    paths:
      - '**/close-pull-request.yml'

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Hi, this PR will be closed automatically. Please do not touch the 'close-pull-request.yml' file."
