name: "File Existence"

on: [push, pull_request, workflow_dispatch]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "README.md"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!