name: Get Workflow Origin Information (PR)
on:
  pull_request:
    branches: ['main']

jobs:
  get-info:
    name: "Get information about the source run"
    runs-on: ubuntu-latest
    outputs:
      sourceHeadRepo: ${{ steps.workflow-run-info.outputs.sourceHeadRepo }}
      sourceHeadBranch: ${{ steps.workflow-run-info.outputs.sourceHeadBranch }}
      sourceHeadSha: ${{ steps.workflow-run-info.outputs.sourceHeadSha }}
      mergeCommitSha: ${{ steps.workflow-run-info.outputs.mergeCommitSha }}
      targetCommitSha: ${{ steps.workflow-run-info.outputs.targetCommitSha }}
      pullRequestNumber: ${{ steps.workflow-run-info.outputs.pullRequestNumber }}
      pullRequestLabels: ${{ steps.workflow-run-info.outputs.pullRequestLabels }}
      targetBranch: ${{ steps.source-run-info.outputs.targetBranch }}
      sourceEvent: ${{ steps.workflow-run-info.outputs.sourceEvent }}
    steps:
      - name: "Get information about the current run"
        uses: potiuk/get-workflow-origin@v1_3
        id: workflow-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

  test-info:
    runs-on: ubuntu-latest
    needs: get-info
    steps:
      - name: Output
        run: |
          echo ${{needs.get-info.outputs.sourceHeadRepo}}
          echo ${{needs.get-info.outputs.sourceHeadBranch}}
          echo ${{needs.get-info.outputs.sourceHeadSha}}
          echo ${{needs.get-info.outputs.mergeCommitSha}}
          echo ${{needs.get-info.outputs.targetCommitSha}}
          echo ${{needs.get-info.outputs.pullRequestNumber}}
          echo ${{needs.get-info.outputs.pullRequestLabels}}
          echo ${{needs.get-info.outputs.targetBranch}}
          echo ${{needs.get-info.outputs.sourceEvent}}