name: 'Delete old artifacts'
on:
  schedule:
    - cron: '0 * * * MON-FRI'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days # Setting this to 0 will delete all artifacts (https://github.com/jkroso/parse-duration)
