name: Repository Dispatch

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: GuillaumeFalourd/useful-actions
          event-type: event-demo
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'