
name: Typos

on: [workflow_dispatch]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Prepare file with mistakes.
      run: echo "The quick brown foxx jumped over the slepy dog." > file.txt 
    - name: Test force pass with mistakes
      uses: crate-ci/typos@v1.0.4
      with: 
        files: ./file.txt

    - name: Prepare file with no mistakes.
      run: echo "The quick brown fox jumped over the sleepy dog." > file.txt 
    - name: Test force pass with no mistakes
      uses: crate-ci/typos@v1.0.4
      with: 
        files: ./file.txt