name: Workflow Dispatch Triggered

on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch Triggered
        run: |
          echo "Workflow triggered successfully by workflow dispatch action!"
          echo Hello ${{ github.event.inputs.input }}
