name: 01 - Default Workflow

on:
  schedule:
  - cron: "0 0 * * MON-FRI" # Runs at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Commands
        run: |
          echo "Hello World"
          echo "You can run any command in your workflow that way with Github Actions"
