name: 05 - Container Workflow

on:
  schedule:
  - cron: "0 4 * * MON-FRI" # Runs at 4:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://guillaumefalourd/ritchiecli:go-1.15.8

    steps:
      - name: Run Commands using Golang
        run: |
              sudo rit -v
              sudo go version