name: "25 - Artifacts between workflows 1"

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v4.4.0
        with:
          name: pr_num
          path: ./pr_num.txt