name: 28 - Create Pull Request (Workflow)

on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    name: create-pull-request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "[example] test_create_pull_request"
          pr_body: "test body."
          github_token: ${{ secrets.GITHUB_TOKEN }}
