name: 31 - Untouchable file

on:
  pull_request_target:
    types: [opened, reopened]
    paths:
      - '**/31-untouchable-file.yml'

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Hi, this PR will be closed automatically. Please do not touch the '31-untouchable-file.yml' file."
