name: 36 - Local Action

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4 # Necessary to access local action
      - name: Local Action Call
        id: local-action
        uses: ./.github/actions/local-action
        with:
          name: "World"
      - name: Local Action Output
        run: echo "${{ steps.local-action.outputs.random }}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4 # Necessary to access local action
      - name: Local Action Call
        id: local-action
        uses: ./.github/workflows/local-action
        with:
          name: "World"
      - name: Local Action Output
        run: echo "${{ steps.local-action.outputs.random }}"