name: 70 - Post Failure

on:
  workflow_dispatch:

jobs:    
  force-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Force job failure
        run: exit 1

  post-failure:
    runs-on: ubuntu-latest
    needs: force-failure
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Do something
        run: echo "Do something"