name: Test 24 # Related to https://stackoverflow.com/questions/71327594/github-action-js-file-return-string-to-be-saved-in-a-variable

on:
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed
      
      - name: set up env var
        run: |
          URL=$(python scripts/test_workflow24.py)
          echo $URL
          echo "URL=$URL" >> $GITHUB_ENV
      
      - name: use env var
        run: echo ${{ env.URL }}

  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Install the node version needed
      
      - name: set up env var
        run: |
          URL=$(node scripts/test_workflow24.js)
          echo $URL
          echo "URL=$URL" >> $GITHUB_ENV
      
      - name: use env var
        run: echo ${{ env.URL }}