name: Test 52 #Related to SO https://stackoverflow.com/questions/73305126/passing-variable-inputs-to-a-resuable-workflow

on:
  push:
  workflow_dispatch:
    inputs:
      branch-to-deploy:
        required: true
        description: The branch to deploy

env:
  SOME_VAR: bla_bla_bla
  ANOTHER_VAR: stuff_stuff
  SERVICE_NAME: products
  BRANCH_NAME: ${{inputs.branch-to-deploy}}

jobs:
  print:
    if: ${{ inputs.branch-to-deploy == "abc" }} || startsWith(${{ inputs.branch-to-deploy }}, 'He')
    name: xyx
    strategy:
      matrix:
        include:
          - server: test-branch
            stage: dev
          - server: test3
            stage: dev
    runs-on: ubuntu-latest
    outputs:
      some_var: ${{ steps.step1.outputs.some_var }}
      another_var: ${{ steps.step1.outputs.another_var }}
      service: products
    steps:
      - run: echo "This is the $BRANCH_NAME environment variable"
      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref }}
      - name: Run matrix
        run: |
          echo ${{ matrix.server }}
          python --version
        env:
          STAGE: ${{  matrix.stage == 'dev' && format('{0}{1}{2}', 'https://', matrix.server, '.mytools.aleno.me/graphql') || 'https://graphql.aleno.me/graphql' }}

  # call_reusable:
  #   if: ${{contains(fromJson('["products", "pull_request"]'), 'products')}}
  #   needs:
  #     - print
  #   uses: GuillaumeFalourd/poc-github-actions/.github/workflows/workflow-tester52-reusable.yml@main
  #   with:
  #     input_var: ${{ needs.print.outputs.some_var }}
  #     another_input_var: ${{ needs.print.outputs.another_var }}
