name: Test 37 #Related to https://stackoverflow.com/questions/72551501/using-if-statements-in-actions

on:
  workflow_dispatch:
    inputs:
      username:
        required: false
        type: string

jobs:
  test:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Inputs username (workflow call)
        if: ${{ inputs.username }} != ''
        run: echo ${{ inputs.username }}

      - name: Inputs username (workflow dispatch)
        if: ${{ github.event.inputs.username }} != ''
        run: echo ${{ github.event.inputs.username }}

      - uses: actions/checkout@v2.3.4 # Necessary to access local action
      
      - name: Local Action Call Without Input
        id: local-action
        uses: ./.github/actions/local-action
        with:
          name: ${{ inputs.username }}

