name: Test 55 #Related to SO https://stackoverflow.com/questions/73643836/prevent-a-job-in-github-action-workflow-file-to-run-in-case-of-an-event

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

# opened: when the PR is opened
# reopened: when the PR is reopened
# synchronize: when the PR description or files are edited
# edited: when editing the title

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB ACTION:" ${{ github.event.action }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  job2:
    runs-on: ubuntu-latest
    if: github.event.action == 'edited'
    steps:
      - run: |
          echo "Pull Request EDITED"
          echo ${{ github.event }}

  job3:
    runs-on: ubuntu-latest
    if: github.event.action != 'edited'
    steps:
      - run: |
          echo "Pull Request NOT EDITED"
          echo ${{ github.event }}
