name: Test 48 #Related to SO https://stackoverflow.com/questions/73193320/use-input-parameter-as-condition-to-skip-a-step

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4 # Necessary to access local action
      - name: Test1 Action Call TRUE
        id: test1-action-true
        uses: ./.github/actions/test1
        with:
          dry_run: true
      - name: Test1 Action Call FALSE
        id: test1-action-false
        uses: ./.github/actions/test1