name: Test 68 # Related to https://stackoverflow.com/questions/74188647/add-variable-value-to-github-action-name

on:
  push:
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # - name: Install dependencies
      #   run: dotnet restore

      # - name: Build
      #   run: dotnet build --configuration Release

      - name: Unit Test 1
        continue-on-error: true
        run: dotnet --no-restore --verbosity normal

      - name: Extract exit Code
        run: echo $?

      - name: Unit Test 2
        continue-on-error: true
        run: 
          dotnet --no-restore --verbosity normal || true
          echo "Check"
          echo $?