name: Test 60 # Related to https://stackoverflow.com/questions/74072206/github-actions-use-variables-in-matrix-definition

on:
  #push:
  workflow_dispatch:
    inputs:
      test1:
        description: "Test1"
        required: false
        default: "test1"
      test2:
        description: "Test2"
        required: false
        default: "test2"
      test3:
        description: "Test3"
        required: false
        default: "test3"

env:
  CARGO_TERM_COLOR: always
  ZEROCOPY_MSRV: 1.61.0
  ZEROCOPY_CURRENT_STABLE: 1.64.0
  ZEROCOPY_CURRENT_NIGHTLY: nightly-2022-09-26

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See `INTERNAL.md` for an explanation of these pinned toolchain versions.
        channel: [ "${{ inputs.test1 }}", "${{ inputs.test2 }}", "${{ inputs.test3 }}" ]
        target: [ "i686-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "arm-unknown-linux-gnueabi", "aarch64-unknown-linux-gnu", "powerpc-unknown-linux-gnu", "powerpc64-unknown-linux-gnu", "wasm32-wasi" ]
        features: [ "" , "alloc,simd", "alloc,simd,simd-nightly" ]
        exclude:
          # Exclude any combination which uses a non-nightly toolchain but enables nightly features.
          - channel: ${{ inputs.test1 }}
            features: "alloc,simd,simd-nightly"
          - channel: ${{ inputs.test2 }}
            features: "alloc,simd,simd-nightly"
    steps:
      - run: |
          echo ${{ matrix.channel }}
          echo ${{ matrix.target }}
          echo ${{ matrix.features }}