name: Test Install Poetry Action # Related to https://github.com/snok/install-poetry/issues/94

on:
  workflow_dispatch:
  #push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows-131:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          version: 1.2.1
          virtualenvs-create: false
  
  build-windows-132:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.2
        with:
          version: 1.2.1
          virtualenvs-create: false