name: Test 81 # Related to https://stackoverflow.com/questions/76313404/how-to-replace-hard-coded-value-with-dynamic-input-variable-in-the-outputs-git

on:
  workflow_dispatch:   
    inputs:
      key_name:
        required: true
        default: 'app_name'

jobs:
  mainjob1:
    runs-on: "ubuntu-latest"
    outputs:
      app_namexx: ${{ steps.run-script.outputs.inputs.key_name }}  
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3
      - id: run-script
        run: echo "${{inputs.key_name}}=test" >> $GITHUB_OUTPUT
      - run: |
          echo "App name as expected: ${{ steps.run-script.outputs.inputs.key_name }}"
          echo "App name hardcoded: ${{ steps.run-script.outputs.app_name }}"

  test:
    runs-on: "ubuntu-latest"
    needs: mainjob1
    steps:
      - run: |
          echo "App name: ${{ needs.mainjob1.outputs.app_namexx }}"

