name: Test 30 # Related to https://stackoverflow.com/questions/71593861/how-to-get-github-actions-matrix-job-name-within-job

on:
  # pull_request:
  #   types: [opened, synchronize]
  workflow_dispatch:
  # push:

jobs:
  my-job:
    name: OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
    steps:
      - run: echo ${{ github.job }}
      - run: |
          JOB_NAME="OS ${{ matrix.os }}"
          echo $JOB_NAME
          echo "JOB_NAME=$JOB_NAME" >> $GITHUB_ENV

      - name: Print JOB_NAME
        run: |
          echo "JOB NAME:" ${{ env.JOB_NAME }}