name: Test 9

on: [workflow_dispatch]

jobs:
  test1:
    runs-on: macos-latest
    steps:
      - name: Run Commands
        run: gcc -v

  test2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: ubuntu-latest
          INSTALL_DEPS: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" && date && brew install gcc && date
          CC: gcc
          CXX: g++
        - os: macos-latest
          INSTALL_DEPS: brew install gcc
          CC: clang
          CXX: clang++
    steps:
      - uses: actions/checkout@v2
      - name: install-dependencies
        run: ${{ matrix.INSTALL_DEPS }}
      - run: gcc -v