name: Test 96 # Related to SO https://stackoverflow.com/questions/78512402/how-to-reuse-script-from-jenkins-in-github-actions?noredirect=1#comment138415710_78512402

on:
  workflow_dispatch:

jobs:
 build:
  runs-on: [ubuntu-latest]
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: List files (Start)
      run: |
          ls
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install Groovy
      run: sudo apt-get update && sudo apt-get install -y groovy
    - name: Run Groovy script
      run: |
        ls -lha
        groovy script.groovy