name: Test 52 #Related to SO https://stackoverflow.com/questions/73305126/passing-variable-inputs-to-a-resuable-workflow

on:
  push:
  workflow_dispatch:

env:
  SOME_VAR: bla_bla_bla
  ANOTHER_VAR: stuff_stuff
  SERVICE_NAME: products

jobs:
  print:
    strategy:
      matrix:
        include:
          - server: test2
            stage: dev
          - server: test4
            stage: dev
          - server: test3
            stage: staging
    runs-on: ubuntu-latest
    outputs:
      some_var: ${{ steps.step1.outputs.some_var }}
      another_var: ${{ steps.step1.outputs.another_var }}
      service: products
    steps:
      - if: ${{ matrix.dev}}
        run: |
          echo ${{ matrix.server }}
          python --version

  call_reusable:
    if: ${{contains(fromJson('["products", "pull_request"]'), 'products')}}
    needs:
      - print
    uses: GuillaumeFalourd/poc-github-actions/.github/workflows/workflow-tester52-reusable.yml@main
    with:
      input_var: ${{ needs.print.outputs.some_var }}
      another_input_var: ${{ needs.print.outputs.another_var }}
