name: Test 41 # Related to https://stackoverflow.com/questions/72704563/github-action-echo-within-an-expression

on:
  workflow_dispatch:

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      # aws: ${{ steps.filter.outputs.aws }}
      # azure: ${{ steps.filter.outputs.azure }}
      # gcp: ${{ steps.filter.outputs.gcp }}
      aws: 'true'
      azure: 'true'
      gcp: 'true'
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Check for changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          aws:
            - added|modified: 'aws/**'
          azure:
            - added|modified: 'azure/**'
          gcp:
            - added|modified: 'gcp/**'

  zip_files:
    runs-on: ubuntu-latest
    needs: [ changes]
    if: ${{ (needs.changes.outputs.aws == 'true') || (needs.changes.outputs.azure == 'true') || (needs.changes.outputs.gcp == 'true') }}
    steps:
      - uses: actions/checkout@v2
      - id: check
        run: |
          if [ '${{ needs.changes.outputs.aws }}' == 'true' ]; then
            echo "::set-output name=aws::aws"
          fi
          if [ '${{ needs.changes.outputs.azure }}' == 'true' ]; then
            echo "::set-output name=azure::azure"
          fi
          if [ '${{ needs.changes.outputs.gcp }}' == 'true' ]; then
            echo "::set-output name=gcp::gcp"
          fi
      - name: check values
        run: |
          echo ${{steps.check.outputs.aws}}
          echo ${{steps.check.outputs.azure}}
          echo ${{steps.check.outputs.gcp}}
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r result.zip "${{steps.check.outputs.aws}}" "${{steps.check.outputs.azure}}" "${{steps.check.outputs.gcp}}"
      - uses: actions/upload-artifact@v4.4.0
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip