name: Test 76 # Related to https://stackoverflow.com/questions/75675348/can-i-use-github-secrets-in-my-npmrc-file-if-so-how/75675523#75675523

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat ./.npmrc
      - name: Replace values
        shell: bash
        env: 
          PAT: ${{ secrets.ACCESS_TOKEN }}
        run: |
          sed -i.back "s|MY_PAT_SECRET|${PAT}|g" ./.npmrc
      - run: cat ./.npmrc